# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "chef/fedora-20"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 3072
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
  end

  config.vm.network "private_network", ip: "10.1.1.2"
  config.hostsupdater.aliases = ["db"]

  config.vm.provision "shell", path: "bootstrap.sh", args: "-e dev -l"

end